config/routes.rb
Rails.application.routes.draw do
  root 'games#new'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'auth/:provider/callback' => 'devise/sessions#create'
    get 'auth/failure' => redirect('/')
  end

  resources :games, only: [:create, :update, :show, :index]

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                   controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  
  namespace :api, path: '/' do
    namespace :v1 do 
      resources :games, only: [:update] do
        resources :boards, only: [:create, :show, :show, :update]
        put '/update_status/:status_code', to: 'games#update_status'
      end
    end
  end
end

app/models/game.rb
class Game < ActiveRecord::Base

  belongs_to :first_player, class_name: 'User', foreign_key: 'first_player_id'
  belongs_to :second_player, class_name: 'User', foreign_key: 'second_player_id'
  has_one :first_player_board, class_name: 'Board', through: :first_player, source: :first_player_board
  has_one :second_player_board, class_name: 'Board', through: :second_player, source: :second_player_board
  
  scope :open_games, -> (id, fid) { where("first_player_id = ? or second_player_id = ?", id, fid) }

  validates :room_name, presence: true
  validates :state, inclusion: { in: ['waiting', 'setup', 'playing', 'over'] }
  
  STATUSES = ['waiting', 'setup', 'playing', 'over']
  PLACEHOLDER_ID = 0

  def is_full?
    second_player_id != 0
  end

  def open?
    !is_full?
  end

  def players
    [first_player, second_player]
  end

  def player_ids
    [first_player_id, second_player_id]
  end

  def update_status(status)
    update_attribute(:state, "#{Game::STATUSES[status.to_i]}" )
  end

  def toggle_current_player
    if current_user_id == first_player_id
      current_user_id = second_player_id
    else
      current_user_id = first_player_id
    end
  end
end

app/controllers/api/v1/games_controller.rb
module Api
  module V1
    class GamesController < Api::V1::ApiController 
      # before_action :ensure_players_belong_in_game, only:[ :show, :update ]
      skip_before_action :authenticate_user!, only: [:update_status]
    
      # used to trigger board status change
      def update_status
        @game = Game.find(params[:game_id])
        @game.update_status(params[:status_code])
        render json: { resp: @game }
      end

      private

      def feedback_factory(msg, status = :ok, start_game = true, custom = '')
        Services::RenderFeedack.new({ msg: msg, status: status,
                              start_game: start_game, custom: custom }).render_message
      end
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :query_scoped_games, only: [:new, :index]
  after_action :setup_boards, only: :update

  def new
    @game = Game.new
    render :new
  end

  def index
    @games = Game.order('created_at desc').page(params[:page]).per(10)
    render :index
  end

  # create game with placeholder player
  # until human player joins
  def create
    @game = Game.new(game_params)
    setup_game_players
    if @game.save
      render :show
    else
      flash[:errors] = @game.errors.full_messages.join("")
      redirect_to root_path
    end
  end

  def update
    @game = Game.find(params[:id])
    @game.second_player_id = current_user.id 
    @game.state = 'setup'
    if @game.save!
      render :show
    else 
      render @game.errors.full_messages
    end
  end

  def show
    @game = Game.find(params[:id])
    render :show
  end

  private
  def game_params
    params.require(:game).permit(:room_name)
  end

  # games where first_player_id or second_player_id == current_user.id
  def query_scoped_games
    @open_games = Game.open_games(current_user.id, current_user.id)
  end
  
  def setup_boards
    @game.player_ids.each do |player_id|
      Services::BoardFactory.new({ game_id: @game.id,
                                   user_id: player_id }).build_board
    end
  end

  def setup_game_players
    @game.first_player_id = current_user.id
    @game.second_player_id = Game::PLACEHOLDER_ID
    @game.current_user_id = current_user.id
  end
end

app/helpers/api/games_helper.rb
module Api::GamesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.haml
.margin-top-140{ 'data-controller': params[:controller], 'data-action': params[:action ]}
  %h1.text-align-center.margin-bot-neg-1 All of the Games
  %table.table-thin.margin-0-auto
    %tr
      %th Room Name
      %th First Player
      %th Created At
      %th Open?
    - @games.each do |game|
      %tr{'data-id': "#{game.id}", 'data-url': "#{game_path(game.id)}"}
        =form_for(game, as: @game, url: game_path(game)) do |f|
          %input{:name => "_method", :type => "hidden", :value => "patch"}
          %td
            #{game.room_name}
          %td
            #{game.first_player.username}
            .display-inline.score.display-none.margin-top-5
              #{'score:' + game.first_player.total_score}
          %td
            #{time_ago_in_words(game.created_at) + ' ago'}
          %td
            #{game.open?}
  .pagination-wrapper
    = paginate @games

app/views/games/new.html.haml
.static_index{ 'data-controller': params[:controller], 'data-action': params[:action]}
  .margin-top-120
    %h1.new-game-header.text-align-center
      Create New Game
    .new-game-container.margin-0-auto
      .inner-game-container
        = image_tag('http://www.baybushwalkers.org.au/wilsons12/wombat.gif', class: 'img-half-size margin-top-neg-50 cursor-pointer', id: 'wombat-img')
        .new-game-wrapper
          = form_for(@game, as: @game, url: games_path(@game)) do |f|
            .field.new-game
              %br
              = f.text_field :room_name, autofocus: true, class: 'input', id:'new-game-field', placeholder: 'room name'
            .actions
              = f.submit 'Create New Game', class: 'main-btn inconsolata-font letter-spacing-2', id: 'new-game-btn'
              = link_to 'Join Existing', games_path, class: 'main-btn', id: 'join-existing'

app/views/games/show.html.haml
.game-body
  %h3= "#{@game.room_name}"
  %canvas.game-canvas{ width: 900, height: 530 }