config/routes.rb
Rails.application.routes.draw do
  root 'games#new'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'auth/:provider/callback' => 'devise/sessions#create'
    get 'auth/failure' => redirect('/')
  end

  resources :games, only: [:create, :update, :show, :index]

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                   controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  
  namespace :api, path: '/' do
    namespace :v1 do 
      resources :games, only: [:update] do
        resources :boards, only: [:create, :show, :show, :update]
        put '/update_status/:status_code', to: 'games#update_status'
      end
    end
  end
end

app/views/layouts/_header.html.haml
- if current_user
  .header
    .profile-image.pull-left
      =image_tag(current_user.picture, class: 'img-circle img-half-size')
    .pull-left.margin-left-10{'data-controller': params[:controller]}
      %span.your-score
        Your Score: #{current_user.total_score} Points
    .pull-right.margin-right-10
      =link_to('Home', root_path) + " | "
      =link_to('Sign Out', users_sign_out_path)
    .flashes
      - flash.each do |key, value|
        %div{:class => "flash #{key}"}= value

  - if @open_games && @open_games.length > 0
    .open-games-header
      current games: 
      - @open_games.each do |game|
        =link_to(game.room_name, game_path(game.id))

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Battleship
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Inconsolata", :rel => "stylesheet", :type => "text/css"}/
  %body
    = render partial: 'layouts/header'
    = yield